version: '3.5'
services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.15
    command: ["--collector.zipkin.http-port=9411"]
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778
      - 16686:16686
      - 14268
      - 14250:14250
      - 9411:9411
    restart: on-failure
